<?php
// Simple HTTP proxy for youtubei.js
// Only allow requests to YouTube hosts to avoid general proxy abuse
$allowed_hosts = [
    'www.youtube.com',
    'youtubei.googleapis.com',
    'music.youtube.com',
    'm.youtube.com',
    'youtube.com'
];

$target_url = isset($_GET['url']) ? $_GET['url'] : '';
if (empty($target_url)) {
    http_response_code(400);
    echo "Missing url parameter";
    exit;
}

$parsed_url = parse_url($target_url);
$host = isset($parsed_url['host']) ? $parsed_url['host'] : '';

$is_allowed = false;
foreach ($allowed_hosts as $allowed) {
    if ($host === $allowed || substr($host, -strlen('.' . $allowed)) === '.' . $allowed) {
        $is_allowed = true;
        break;
    }
}

if (!$is_allowed) {
    http_response_code(403);
    echo "Forbidden host: " . htmlspecialchars($host);
    exit;
}

$method = $_SERVER['REQUEST_METHOD'];

// Parse incoming headers
$headers = [];
foreach (getallheaders() as $name => $value) {
    $lower_name = strtolower($name);
    // Skip host and other headers that should be generated by curl
    if (in_array($lower_name, ['host', 'content-length', 'accept-encoding', 'connection'])) {
        continue;
    }
    $headers[] = "$name: $value";
}

$body = file_get_contents('php://input');

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $target_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, true);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_MAXREDIRS, 5);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // For simplicity

if ($method === 'POST') {
    curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
}

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$response = curl_exec($ch);
if (curl_errno($ch)) {
    http_response_code(500);
    echo 'Proxy Curl error: ' . curl_error($ch);
    exit;
}

$header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
$http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

$response_headers = substr($response, 0, $header_size);
$response_body = substr($response, $header_size);

http_response_code($http_code);

// Forward response headers
$response_headers_lines = explode("\r\n", $response_headers);
foreach ($response_headers_lines as $line) {
    if (empty($line)) continue;
    $lower_line = strtolower($line);
    // Skip HTTP status line and encoding headers
    if (strpos($lower_line, 'http/') === 0) continue;
    if (strpos($lower_line, 'transfer-encoding:') === 0) continue;
    if (strpos($lower_line, 'content-encoding:') === 0) continue;
    if (strpos($lower_line, 'connection:') === 0) continue;
    if (strpos($lower_line, 'access-control-allow-origin:') === 0) continue;
    
    header($line);
}

// Add CORS headers
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");

echo $response_body;
